# First Window
<FirstWindow>:
    name: "first"
    MDBoxLayout:
        size_hint: 1, 1
        padding: 5
        MDFlatButton:
            text: 'Scan'
            md_bg_color: 'red'
            theme_text_color: 'Custom'
            text_color: 'white'
            pos_hint: {'center_x': .5, 'center_y': .5}
            size_hint_x: .2
            on_release:
                root.start_bluetooth_scan()
    